[package]
name = "onlocal-ui"
version = "0.1.0"
description = "OnLocal GUI"
authors = ["OnLocal Team"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-shell = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "onlocal_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "onlocal-ui"
path = "src/main.rs"
bench = false
